FORMAT: 1A
HOST: https://www.youthweb.net

# Youthweb API

Dies ist die offizielle API von [youthweb.net](https://youthweb.net).

Aktuelle Version: 0.1 (2014-12-17)

Status: Alpha

Github Repository: https://github.com/youthweb/youthweb-api

## Authentication

Keine. Diese Version ist read-only.

# Group Account

## Account Stats [/index.php?action=account&cat=stats]

### Retrieve the account stats [GET]
+ Response 200 (application/json)

    Der Response hat diesen Inhalt:
    - user_total: 5503 (integer) - Die Anzahl aller User
    - user_online: 74 (integer) - Die Anzahl der User, die online sind

    + Body

            {"data":{"user_total":5503,"user_online":74}}
