FORMAT: 1A
HOST: https://youthweb.net

# Youthweb API - Errors

Hier werden Fehler und Fehlermeldungen der API getestet

# Group Stats

## Account Stats [/stats/account]

### Retrieve the account stats without content-type header [GET]
+ Request

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

+ Response 415 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

    + Body

            {"errors":[{"title":"Unsupported Media Type","detail":"You're using an unsupported Content-Type. You have to use the Content-Type application/vnd.api+json"}]}

### Retrieve the account stats with content-type header and parameter [GET]
+ Request (application/vnd.api+json; parameter=value)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

+ Response 415 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

    + Body

            {"errors":[{"title":"Unsupported Media Type","detail":"You're using an unsupported Content-Type. You have to use the Content-Type application/vnd.api+json"}]}

### Retrieve the account stats with accept header without version parameter [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 406 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

    + Body

            {"errors":[{"title":"Not Acceptable","detail":"You havn't specified the API version in the Accept Header. You have to use Accept application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4"}]}

### Retrieve the account stats without accept header [GET]
+ Request (application/vnd.api+json)

+ Response 406 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

    + Body

            {"errors":[{"title":"Not Acceptable","detail":"You havn't specified the API version in the Accept Header. You have to use Accept application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4"}]}
