FORMAT: 1A
HOST: https://api.youthweb.net

# Youthweb API - Errors

Hier werden Fehler und Fehlermeldungen der API getestet.

# Group General

## Index [/]

### Request no resource [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 404 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"404","title":"Resource not found"}]}

## Invalid JSON API [/users/187654/posts]

### Create a post with invalid JSON API [POST]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Attributes

        + data (object)
            + type: `posts` (string)
            + attributes (object)
                + `content`: `Lorem ipsum dolor sit amet, sed libris elaboraret eu.` (string) - Der Post-Inhalt
        + errors (array)
            + (object)
                `detail`: `The members data and errors MUST NOT coexist in the same document.` (string)

+ Response 400 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"400","title":"Bad Request","detail":"Your request format must be valid JSON API. The properties `data` and `errors` MUST NOT coexist in Document."}]}

# Group Stats

## Account Stats [/stats/account]

### Retrieve the account stats without content-type header [GET]
+ Request

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 415 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"415","title":"Unsupported Media Type","detail":"You're using an unsupported Content-Type. You have to use the Content-Type application/vnd.api+json"}]}

### Retrieve the account stats with content-type header and parameter [GET]
+ Request (application/vnd.api+json; parameter=value)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 415 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"415","title":"Unsupported Media Type","detail":"You're using an unsupported Content-Type. You have to use the Content-Type application/vnd.api+json"}]}

### Retrieve the account stats with accept header without version parameter [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 406 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"406","title":"Not Acceptable","detail":"You havn't specified the API version in the Accept Header. You have to use Accept application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10"}]}

### Retrieve the account stats without accept header [GET]
+ Request (application/vnd.api+json)

+ Response 406 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"406","title":"Not Acceptable","detail":"You havn't specified the API version in the Accept Header. You have to use Accept application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10"}]}

## Forum Stats [/stats/forum]

### Retrieve the forum stats with a deprecated version parameter [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.7

+ Response 200 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"data":null,"meta":{"warnings":["You have specified a deprecated API version. Please use the current API version 0.10"]}}

## Group Stats [/stats/group]

### Retrieve the group stats with a unsupported version parameter [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.4

+ Response 406 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"406","title":"Not Acceptable","detail":"You have specified an unsupported API version. Please use the current API version 0.10"}]}

# Group Users

## Me [/me]

### Request the /me resource without Bearer token [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 401 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"401","title":"Unauthorized"}]}

# Group Posts

## Forbidden Posts [/posts/f5a5a2c3-041b-4985-907c-74a2131efc98]

### Request a forbidden post [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 403 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"403","title":"Forbidden"}]}

## Not existing Posts [/posts/45a5a2c3-041b-4985-907c-74a2131efc98]

### Request a not existing post [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 404 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"404","title":"Resource not found"}]}

## Create Post on not existing user [/users/987654/posts]

### Create a post on an not existing user [POST]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Attributes

        + data (Post Created)

+ Response 404 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"404","title":"Resource not found"}]}

## Create Post without permission [/users/487654/posts]

### Create a post without permission [POST]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Attributes

        + data (Post Created)

+ Response 403 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"403","title":"Forbidden"}]}

## Create Post with content errors [/users/287654/posts]

### Create a post with empty content [POST]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Attributes

        + data (object)
            + type: `posts` (string)
            + attributes (object)
                + `title`: `The post title` (string) - Der Title, kann auch leer sein
                + `content`: `` (string) - Der Post-Inhalt
                + `view_allowed_for`: `users` (string) - Wer kann diesen Post sehen? (`all`, `users`, `friends` oder `authors`)
                + `comments_allowed`: true (boolean) - Kann dieser Post kommentiert werden?

+ Response 400 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"422","title":"Unprocessable Entity","detail":"The field `attributes.content` can't be empty."}]}

### Create a post with missing content [POST]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Attributes

        + data (object)
            + type: `posts` (string)
            + attributes (object)
                + `title`: `The post title` (string) - Der Title, kann auch leer sein
                + `view_allowed_for`: `users` (string) - Wer kann diesen Post sehen? (`all`, `users`, `friends` oder `authors`)
                + `comments_allowed`: true (boolean) - Kann dieser Post kommentiert werden?

+ Response 400 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"422","title":"Unprocessable Entity","detail":"The field `attributes.content` must be set."}]}

# Group Events

## Request an event [/events/4567]

### Request an event without authorization [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 401 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"401","title":"Unauthorized"}]}

## Not existing event [/events/404]

### Request a not existing event [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

+ Response 404 (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json, application/vnd.api+json; net.youthweb.api.version=0.10

    + Body

            {"errors":[{"status":"404","title":"Resource not found"}]}

# Data Structures

## Post Created (object)

+ type: `posts` (string)
+ attributes (object)
    + `title`: `The post title` (string) - Der Title, kann auch leer sein
    + `content`: `Lorem ipsum dolor sit amet, sed libris elaboraret eu.` (string) - Der Post-Inhalt
    + `view_allowed_for`: `users` (string) - Wer kann diesen Post sehen? (`all`, `users`, `friends` oder `authors`)
    + `comments_allowed`: true (boolean) - Kann dieser Post kommentiert werden?
